inducer/pytools

pytools/__init__.py
This should fix the issue described in #15.
=> Set use_late_start_logging=False if stdin is None

pytools/obj_array.py
1) Fix a typo
2) Rename decorator for consistency with others
=> Fixes to obj_array.py

README.rst
=> Fix a README typo

pytools/version.py
=> Bump version for addition of deprecate_kwarg

pytools/tag.py, pytools/version.py, test/test_persistent_dict.py
=> Support pytools.tag in persistent_dict

pytools/__init__.py, pytools/version.py
=> resolve_name backport

pytools/__init__.py
Reported on the Firedrake slack channel.
=> ProcessLogger: account for sys.stdin being closed

pytools/obj_array.py, test/test_pytools.py
=> Fix some typos after decorator removal

pytools/tag.py, pytools/version.py, test/test_pytools.py
cc @thomasgibson @nchristensen
=> Un-methodize check_tag_uniqueness and normalize_tags

pytools/__init__.py
=> Add Matt's sphere_sample

doc/Makefile, pytools/__init__.py, test/test_pytools.py
Found another algorithm to generate points on a sphere in a vaguely regular pattern and thought of adding it too.
=> Sample points on sphere using the Fibonacci lattice

pytools/__init__.py, pytools/batchjob.py, pytools/convergence.py, pytools/debug.py, pytools/lex.py, pytools/persistent_dict.py, pytools/prefork.py, pytools/py_codegen.py, pytools/spatial_btree.py, pytools/stopwatch.py, setup.py, test/test_pytools.py
Just remembered I had this lying around from a few weeks back. 
A good chunk is automated by `pyupgrade`, but it has some manual f-strings changes, but hopefully no typos :crossed_fingers:.
=> pyupgrade more

pytools/convergence.py
* Adds some types
* Adds methods to docs
* Adds some asserts in `add_data_point` to make sure that it doesn't get weird non-numeric data
=> Improve EOCRecorder docs and checks

pytools/convergence.py
Sorry about the breakage! This seems to fix it locally.
=> Fix check in EOCRecorder

test/test_pytools.py
Added some more tests to check the inputs to `add_data_point`. Hopefully catch the breakage earlier next time!
=> Add more tests to EOCRecorder

pytools/persistent_dict.py
Based on https://github.com/inducer/pyopencl/pull/504
=> restructure lock file timeout

.github/workflows/ci.yml, .gitlab-ci.yml, pytools/__init__.py
=> CI improvements

doc/conf.py, pytools/tag.py
=> Fix type annotation of `Taggable.tags_of_type`

pytools/tag.py, test/test_pytools.py
=> add IgnoredForEqualityTag

test/test_graph_tools.py
=> add simple reverse_graph test

pytools/graph.py, pytools/tag.py, test/test_graph_tools.py
=> Add `reverse_graph`

.github/workflows/ci.yml, pytools/convergence.py
- make sure mypy considers numpy
- fix types in add_data_point
=> convergence: small mypy fixes

pytools/graph.py, test/test_graph_tools.py
(from #151)
- Iterable -> Collection
- a few type annotations
- some spelling fixes
=> graph: small fixes

doc/conf.py, pytools/graph.py
=> graph: create GraphT

pytools/debug.py
Was causing the error `TypeError: can only concatenate tuple (not "list") to tuple`
=> refdebug: concatenate tuple with tuple

pytools/__init__.py, pytools/test/test_pytools.py
=> Add `unique` function.

pytools/tag.py, pytools/test/test_pytools.py
The attached test fails without this PR.
*Please squash*
=> Tag: implement eq, repr for DottedName

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
=> KeyBuilder: support ABC, ABCMeta

.github/workflows/ci.yml, pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
The test fails without this PR. Followup of #147.
=> KeyBuilder: fix hashing of dataclasses/attrs, add test

pytools/persistent_dict.py
=> remove deprecated appdirs module

README.rst, doc/conf.py, pytools/persistent_dict.py, pytools/test/test_persistent_dict.py, run-mypy.sh
=> PersistentDict: better docs, type annotations

pytools/tag.py, pytools/test/test_pytools.py
(minimum required version is 3.8 currently)
=> clean up some version_info checks

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
=> KeyBuilder: Fix time hashing

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
Should address the performance issues seen in #227.
=> PersistentDict: allow setting sync

pytools/tag.py
=> tag.py: try importing from typing first

doc/conf.py, pytools/__init__.py, pytools/convergence.py, pytools/test/test_pytools.py
=> more unique functions

doc/conf.py, pyproject.toml, pytools/__init__.py, pytools/batchjob.py, pytools/codegen.py, pytools/convergence.py, pytools/datatable.py, pytools/debug.py, pytools/graph.py, pytools/graphviz.py, pytools/lex.py, pytools/mpi.py, pytools/mpiwrap.py, pytools/obj_array.py, pytools/prefork.py, pytools/py_codegen.py, pytools/spatial_btree.py, pytools/stopwatch.py, pytools/test/test_data_table.py, pytools/test/test_dataclasses.py, pytools/test/test_graph_tools.py, pytools/test/test_math_stuff.py, pytools/test/test_mpi.py, pytools/test/test_persistent_dict.py, pytools/test/test_py_codegen.py, pytools/test/test_pytools.py, pytools/version.py
Also enables `from __future__ import annotations`.
=> ruff: enable UP006 and UP007

pytools/test/test_persistent_dict.py
=> fix NaN test
