inducer/pytools

setup.py
Since commit d855850c, function `six.moves.intern` is used in pytools,
but this function appeared only in six 1.8.0.
This commit prevents an error while importing pytools with an older six installed.
See: [six CHANGES](https://bitbucket.org/gutworth/six/src/1991f8b5b654f077e773f05695a08e0506b7367f/CHANGES?at=default&fileviewer=file-view-default)
=> Require at least six 1.8.0 (for six.moves.intern)

pytools/prefork.py
This request cleans up the preforking module and adds support for asynchronous invocations.  This is accomplished by three new methods: `call_async`, `wait` and `waitall`.  The deprecated method `call_capture_stdout` has also been removed.
Note that it is not currently possible to capture the output from asynchronous processes.  Doing this right is somewhat fiddly as the OS will only buffer so much output from a process before blocking it (waiting on the parent to `.communicate` with it).  This is difficult to accomplish without moving towards threading which would be an additional complication.
Note also that the module is still thread safe.  Only one thread from the parent may call into the prefork routines at any one time.  While this can be worked around it probably does not warrant …
=> Async Support For Prefork

test/test_pytools.py
test_spatial_btree currently fails if numpy is not available.
test_p_convergence_verifier uses the pytest importorskip function to skip the test when numpy is not available.
This change does (adds) the same for test_spatial_btree.
Also, while it is noted that numpy was made an explicit dependency in https://github.com/inducer/pytools/commit/c15d5642bf460a53b990fb053457fc2e13e8241b, if numpy (given its large footprint and compiler/toolchain requirements) is not actually compulsory, or is only required for a few functions or methods in pytools, it would be great to make numpy an ```extras_require``` with a note/comment about what features require it.
=> Import numpy or skip for test_spatial_btree

pytools/__init__.py
A very weird bug: The order of base classes actually matters here,
because if __hash__ and __eq__ are defined in the wrong order,
__hash__ will get deleted (in 3). MWE:
```
class X(object):
def __eq__(self, other):
return True
class Y(object):
def __hash__(self):
return 0
class Z1(Y,X):
pass
class Z2(X,Y):
pass
hash(Z1())
hash(Z2())
```
=> [bugfix] Use base classes for ImmutableRecord in correct order

doc/index.rst, doc/misc.rst, pytools/codegen.py, pytools/py_codegen.py, pytools/version.py
This change takes common code generation functionality out of
pytools.py_codegen and makes it a separate module.
A language-independent parent class of PythonCodeGenerator is also
added.
The version is bumped to 2020.4
=> Add pytools.codegen

pytools/__init__.py
See https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables
for specification.
- Outputs a table that is a valid GFM table, and gets rendered automatically as a table on GitHub.
- Adds column alignment specification and makes output respect it.
=> add github-flavored markdown and aligned output for Table

pytools/__init__.py
By default, it seems like python uses `Python-urllib/<version>`, which I guess some servers block.
=> Add a user agent

pytools/persistent_dict.py
=> Numpy 1.20 compat

pytools/__init__.py, test/test_pytools.py
Went ahead and tried using `object.__setattr__` in `memoize_method` and `keyed_memoize_method`. What do you think?
=> memoize_method for frozen classes

pytools/__init__.py, pytools/persistent_dict.py, pytools/version.py, test/test_persistent_dict.py, test/test_pytools.py
@kaushikcfd would you mind taking a look? This addresses the inability to do `sorted()` for frozenset/dict hashing when those contain `Tag` et al. in https://github.com/inducer/loopy/pull/245.
cc @nchristensen
=> Unordered hashing

pytools/__init__.py
This avoid confusing error messages having
"During handling of the above exception, another exception occurred"
=> Better exception message when exceptions occur inside memoized methods

pytools/__init__.py
Can now do
```
with ProcessTimer() as p:
print(p)
```
Also removed support for python<3.3, since pytools advertises >3.6.
=> Stringify ProcessTimer

pytools/tag.py
This should have helped catch some errors in [Pytato](https://github.com/inducer/pytato), as the taggable-type didn't have a `.copy` defined.
Draft because:
=> make Taggable.copy an abstractmethod

pytools/__init__.py, pytools/convergence.py
Set the default to `markdown` instead of the previous `ascii` since the tables look pretty much the same and this is easier to copy paste in here.
=> Allow choosing table type in EOCRecorder

pytools/persistent_dict.py, setup.py
Seems to be the prefered maintained alternative these days (see https://github.com/psf/black/pull/2375). Not quite sure what do to in `setup.py` though. Just replace `appdirs` with `plaformdirs` in `install_requires`?
For context, for some reason `appdirs` disappeared from my venv on porter (likely due to `--system-site-packages`) and `platformdirs` was there.
=> Prefer platformdirs to appdirs if available

pytools/prefork.py
This warning has been confusing our users for a while as when our main process dies due to a SEGFAULT this warning gets printed, leading to users believing this is the issue.  As is, the warning does not add much utility, so this PR simply removes it and has the process terminate gracefully.
=> Remove a spurious warning.

pytools/convergence.py
Includes the overall order of convergence inside the table so that it's easier to copy paste the whole thing (into Github). Looks something like this:
h           | Error       | Running EOC
:-----------|:------------|:------------
1.00000e+00 | 1.00000e-01 |            
5.00000e-01 | 1.00000e-02 |  3.32      
3.33333e-01 | 1.00000e-03 |  5.68      
Overall     | ---         |  6.99
=> Include overall EOC in table

pytools/__init__.py, pytools/convergence.py, test/test_pytools.py
This adds a couple of things:
* type annotations to `Table`
* adds some checks when adding rows to the table.
* removes some duplication in getting alignements and column widths in the table stringifiers.
* adds a `merge_tables` that takes a bunch of tables and returns a single table with all the columns concatenated
* uses that to implement a `stringify_eocs` that merges a bunch of `EOCRecorders` into a single table.
=> Add table merging

pytools/tag.py
Based on https://github.com/inducer/arraycontext/pull/147#issuecomment-1046368865.
It's not safe to assume `copy` is the right verb for tag application, it's taken e.g. for `pyopencl.array.Array`. Leave more of the actual detail to the subclass.
cc @alexfikl @kaushikcfd
=> Taggable: Do not force `copy` for tag setting

doc/conf.py, pytools/tag.py, setup.py
Upon reviewing https://github.com/inducer/arraycontext/pull/154, I found myself very much not loving the type names I was looking at. @alexfikl, could you take a look if this seems sane? (I'll do a pytools release once some version of this is in.)
=> Fix type names in `pytools.tag`

setup.py
Needs a version that includes the `Self` type.
=> Tighten typing_extensions version requirement

pytools/__init__.py, test/test_pytools.py
Based on the now-deprecated [distutils.util.strtobool](https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool).
Intended to make code like https://github.com/inducer/pytato/blob/a0fa84a5ca17a32f57431b8d67d0383f4c94839c/pytato/__init__.py#L32-L40 more robust.
=> add strtobool()

pytools/__init__.py, test/test_pytools.py
- show fully qualified name by default
- better handling of nested classes via `__qualname__`
- add test
- add type annotations, better doc
before:
`
{'queue': CommandQueue, 'shape': tuple(int,int), 'dtype': dtype[float64], 'strides': tuple(int,int), 'events': list(Event), 'nbytes': int, 'size': int, 'allocator': SVMPool, 'base_data': PooledSVM, 'offset': int, 'context': Context, '_flags': NoneType, 'tags': frozenset(), 'axes': tuple(Axis,Axis)}
`
after:
`
{'queue': pyopencl._cl.CommandQueue, 'shape': tuple(int,int), 'dtype': dtype[float64], 'strides': tuple(int,int), 'events': list(pyopencl._cl.Event), 'nbytes': int, 'size': int, 'allocator': pyopencl._cl.SVMPool, 'base_data': pyopencl._cl.PooledSVM, 'offset': int, 'context': pyopencl._cl.Context, '_flags': NoneType, 'tags': frozenset(), …
=> typedump: type improvements

pytools/persistent_dict.py, test/test_persistent_dict.py
=> persistent_dict: add complex hashing, numpy scalar hashing

README.rst
(this has been moved to logpyle, as the comment a bit lower indicates)
=> remove pytools.log reference from README

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
The three test classes (not objects) are unhashable without this PR.
=> KeyBuilder: allow hashing of classes that define update_persistent_hash

pytools/tag.py, pytools/test/test_persistent_dict.py
Needs #196.
Hashing is now handled directly through the dataclass.
=> Tag: remove update_persistent_hash

pytools/test/test_persistent_dict.py
Found using `ruff check --select NPY201 .` as suggested in the numpy 2.0 migration guide.
=> Guard deprecated usage of longfloat and longcomplex

pytools/persistent_dict.py
also removes update_checksum, which appears to be unused
=> PersistentDict: replace _make_dir_recursively with os.makedirs

.github/workflows/ci.yml, pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
`appdirs` and `platformdirs` do not handle `XDG_CACHE_HOME` on macOS: https://github.com/platformdirs/platformdirs/issues/269 https://github.com/platformdirs/platformdirs/issues/4, and there seems to be no other way to select a custom cache path via platformdirs on macOS at all.
_This adds MacOS pytest to CI, the 'Required for merge' tests need to be adjusted in the GitHub repo config._
=> PersistentDict: honor XDG_CACHE_HOME on MacOS

pytools/__init__.py, pytools/test/test_pytools.py
This is a proof-of-concept and is ready for a first look @inducer. I'm not sure if there is a better way to do this.
=> Record: make field ordering deterministic, add test

doc/conf.py, pytools/persistent_dict.py
Edit: What do you think of renaming the class to `PersistentKeyBuilder` or `PersistentHashBuilder`? We could keep the old name as an alias. This could clarify the goal of the KeyBuilder, as well as its connection to `PersistentDict`.
=> improve KeyBuilder documentation

pytools/__init__.py, pytools/test/test_pytools.py
Somewhat of a (partial) alternative to #207.
=> Record: make __repr__ deterministic, add test

pytools/__init__.py
Removes ~29,000 warnings from the doctest.
=> remove get_read_from_map_from_permutation, get_write_to_map_from_permutation

pytools/persistent_dict.py
Passes through IntegrityErrors that are not ReadOnlyEntryErrors
=> PersistentDict: smarter WOPD.store

pytools/__init__.py, pytools/graph.py, pytools/mpiwrap.py, pytools/persistent_dict.py, pytools/stopwatch.py, setup.cfg
While playing with #235 and #237 to fix the mypy issues, I had some more random fixes sitting around.
This essentially removes the `ignore_errors = True` in `setup.cfg` for some modules and fixes the errors that popped up. There's a bunch of stuff in `persistent_dict.py` that probably requires a careful look.
cc @matthiasdiener since you typed most of `PersistentDict`.
=> Fix some typing issues

pyproject.toml, pytools/__init__.py, pytools/batchjob.py, pytools/datatable.py, pytools/debug.py, pytools/graph.py, pytools/lex.py, pytools/persistent_dict.py, pytools/spatial_btree.py, pytools/tag.py, pytools/test/test_graph_tools.py, pytools/test/test_persistent_dict.py
Same issue as for `mypy` in https://github.com/inducer/modepy/pull/88.
This adds a few more commits with extra rules and fixes, so probably best looked at commit-by-commit.
=> pyproject: hack around to make editable install work

.pylintrc-local.yml, pyproject.toml, pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
I don't know how much of a bottleneck the hash computation is in mirgecom compiles, but at the same time, I can't think of a good reason to not do this. Our use case very much falls into the "many small messages" category, so this graph is pretty compelling:
(from https://cr.yp.to/siphash/siphash-20120918.pdf)
A few things need to happen in order to make this go:
cc @matthiasdiener
=> Use siphash for persistent hashing

.github/workflows/ci.yml, pytools/__init__.py, pytools/datatable.py, pytools/debug.py, pytools/graph.py, pytools/persistent_dict.py, pytools/prefork.py, pytools/spatial_btree.py, pytools/test/test_pytools.py
This removes all the unused suppressions reported by `--enable=I0021`. I'm using pylint 3.2.5 on python 3.12.4, so I imagine not all of these will still pass on the CI, but hopefully some :grin: 
EDIT: That's weird.. I really didn't expect all those `no-member` ones to pass. Oh well!
=> Remove a bunch of unused pylint supressions

pyproject.toml, pytools/tag.py, pytools/test/test_persistent_dict.py, pytools/test/test_pytools.py, run-mypy.sh
- Better type annotations
- Remove IgnoredForEqualityTag
- Have tag_dataclass use dataclass_transform
- Drop fallback from ._with_new_tags to .copy
- Allow Taggable.tags to be a read-only attribute
- Enable strict typing for pytools.tag
=> Modernize `pytools.tag`

.github/workflows/ci.yml, pyproject.toml, pytools/persistent_dict.py
From #242:
> I don't know how much of a bottleneck the hash computation is in mirgecom compiles, but at the same time, I can't think of a good reason to not do this.
I maintain `pytools` and `pyopencl` on Void Linux and, as long as the hash interface is equivalent, making `siphash24` optional will slightly reduce the maintenance burden of carrying these packages alongside the rest of the numerical stack.
=> persistent_dict: make siphash24 optional

pyproject.toml, typos.toml
Moves the `typos.toml` config and removes the configuration file.
=> pyproject: move typos.toml

doc/upload-docs.sh, pyproject.toml, pytools/__init__.py, pytools/convergence.py, pytools/graph.py, pytools/persistent_dict.py, pytools/tag.py, pytools/test/test_pytools.py
Seems to fix the issues from https://github.com/inducer/arraycontext/pull/275
=> tag: only import typing_extensions when TYPE_CHECKING

pytools/persistent_dict.py
=> KeyBuilder: use system byteorder to match numpy

pytools/graph.py, pytools/test/test_graph_tools.py, run-mypy.sh
- Moves tag propagation graph generation logic from [pytato](https://github.com/inducer/pytato/pull/494) to pytools
=> Tag propagation graph generation

pyproject.toml, pytools/__init__.py, pytools/graph.py, pytools/tag.py
Conditional dependencies are too bug-prone, plus the catchy imports are super verbose.
=> Unconditionally depend on `typing-extensions`

pytools/__init__.py
=> Table: add raw output

.github/workflows/ci.yml, pyproject.toml, pytools/__init__.py, pytools/codegen.py, pytools/convergence.py, pytools/datatable.py, pytools/graph.py, pytools/mpi.py, pytools/persistent_dict.py, pytools/spatial_btree.py, pytools/stopwatch.py, pytools/tag.py, pytools/test/test_data_table.py, pytools/test/test_graph_tools.py, pytools/test/test_persistent_dict.py, pytools/test/test_pytools.py
Had some time to waste and tried bumping this up to 3.10. `ruff` was very noisy, but easily fixable :D
There were a lot of places that wanted `zip(..., strict=True)` and will need to check if it actually makes sense (?).
=> Bump min Python to 3.10

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
The attached test fails with numpy 1.26.4 without this PR.
=> KeyBuilder: support np.bool{,_} for numpy<2

pytools/prefork.py, run-mypy.sh
Mostly straightforward, but the socket communication is pretty much ignored for typing.
Don't quite recall, but I think some other package required typing `call_capture_output`, so went ahead and typed the whole thing.
=> mypy: add strict typing to prefork

pytools/__init__.py, pytools/test/test_dataclasses.py
Inspired by https://github.com/inducer/pytato/pull/563.
cc @matthiasdiener (what do you think?)
=> `opt_frozen_dataclass`: Enable hashing with -O

.github/workflows/ci.yml, pytools/test/test_dataclasses.py
=> also run dataclasses test with optimizations enabled

pytools/graph.py, pytools/test/test_graph_tools.py
Updates `get_reachable_nodes` to take an optional set containing nodes that should be ignored (effectively partition points) in an undirected graph. Also updates the corresponding test to account for this new feature.
=> Allow `get_reachable_nodes` to be restricted to partitions

pytools/persistent_dict.py, pytools/test/test_persistent_dict.py
Fixes #262. Followup of #259, #260, #261.
Reverts #260.
Closes #261.
TODO:
=> fix numpy scalar hash for bigendian

README.rst
Forgot to push this yesterday. It updates the link for the CI badge so that it doesn't say "no status" :grin:
=> Update links for badges in README

pytools/py_codegen.py, pytools/test/test_py_codegen.py
(similar to https://documen.tician.de/genpy/reference.html#genpy.Function)
=> PythonFunctionGenerator: add decorator support

.github/workflows/ci.yml, pyproject.toml, pytools/persistent_dict.py
Closes https://github.com/inducer/pyopencl/issues/827
=> Go back to requiring siphash24

.basedpyright/baseline.json, doc/conf.py, pyproject.toml, pytools/__init__.py, pytools/obj_array.py
@alexfikl @majosm What do you think of this? 
Object arrays are super-duper in the way of the type checker understanding hierarchies of array containers. I can't for the life of me figure out how to teach numpy to take any old object as its  dtype:
```
x: np.ndarray[tuple[int], np.dtype[ArithmeticExpression]]
```
results in
```
/home/andreas/src/pytools/pytools/obj_array.py:90:36 - error: Type "ArithmeticExpression" cannot be assigned to type variable "_ScalarT_co@dtype"
  Type "ArithmeticExpression" is not assignable to upper bound "generic[Any]" for type variable "_ScalarT_co@dtype"
    Type "ArithmeticExpression" is not assignable to type "generic[Any]"
      "ExpressionNode" is not assignable to "generic[Any]" (reportInvalidTypeArguments)
```
In addition, shape-precise typing for …
=> Make a type-checking-only `ObjectArray` type
